import logo from "/assets/images/logo.png";
import fundoHd from "/assets/images/fundoHd.png";
import fundoIn1 from "/assets/images/fundoIn1.png";
import fundoIn2 from "/assets/images/fundoIn2.png";
import setaR from "/assets/images/setaR.png";
import setaL from "/assets/images/setaL.png";
import estrela from "/assets/images/estrela.png";
import ponto from "/assets/images/ponto.png";
import dinheiro from "/assets/images/dinheiro.png";
import servico1 from "/assets/images/servico1.png";
import servico2 from "/assets/images/servico2.png";
import servico3 from "/assets/images/servico3.png";
import servico4 from "/assets/images/servico4.png";
import servico5 from "/assets/images/servico5.png";
import sobre from "/assets/images/sobre.png";

export const logoImg = logo;
export const fundoImgHd = fundoHd;
export const fundoImgIn1 = fundoIn1;
export const fundoImgIn2 = fundoIn2;
export const setaRImg = setaR;
export const setaLImg = setaL;
export const dinheiroImg = dinheiro;
export const pontoImg = ponto;
export const estrelaImg = estrela;
export const servico1Img = servico1;
export const servico2Img = servico2;
export const servico3Img = servico3;
export const servico4Img = servico4;
export const servico5Img = servico5;
export const sobreImg = sobre;
