import logo from "/assets/images/logo.png";
import fundoHd from "/assets/images/ernest-brillo-9_vReDaom2Q-unsplash.jpg";
import fundoIn1 from "/assets/images/naufan-rusyda-faikar-tflgTma9qeA-unsplash.jpg";
import fundoIn2 from "/assets/images/naufan-rusyda-faikar-d4ub6O8zXtU-unsplash.jpg";
import setaR from "/assets/images/setaR.png";
import setaL from "/assets/images/setaL.png";
import estrela from "/assets/images/star.jpeg";
import ponto from "/assets/images/pin.png";
import dinheiro from "/assets/images/dindin.jpg";
import servico1 from "/assets/images/servico1.png";
import servico2 from "/assets/images/servico2.png";
import servico3 from "/assets/images/servico3.png";
import servico4 from "/assets/images/servico4.png";
import servico5 from "/assets/images/servico5.png";
import sobre from "/assets/images/sobre.png";

export const logoImg = logo;
export const fundoImgHd = fundoHd;
export const fundoImgIn1 = fundoIn1;
export const fundoImgIn2 = fundoIn2;
export const setaRImg = setaR;
export const setaLImg = setaL;
export const dinheiroImg = dinheiro;
export const pontoImg = ponto;
export const estrelaImg = estrela;
export const servico1Img = servico1;
export const servico2Img = servico2;
export const servico3Img = servico3;
export const servico4Img = servico4;
export const servico5Img = servico5;
export const sobreImg = sobre;
