import logo from "/assets/images/LogoFundo.png";
import fundoHd from "/assets/images/ernest-brillo-9_vReDaom2Q-unsplash.jpg";
import fundoIn1 from "/assets/images/naufan-rusyda-faikar-tflgTma9qeA-unsplash.jpg";
import fundoIn2 from "/assets/images/naufan-rusyda-faikar-d4ub6O8zXtU-unsplash.jpg";
import setaR from "/assets/images/setaR.png";
import setaL from "/assets/images/setaL.png";
import estrela from "/assets/images/round-icons-uq_IHmkIUlA-unsplash.png";
import ponto from "/assets/images/pin.png";
import dinheiro from "/assets/images/dindin.jpg";
import servico1 from "/assets/images/soham-banerjee-SAFF_1rWBqE-unsplash.jpg";
import servico2 from "/assets/images/manufacturing-supervisor-jobs.jpg";
import servico3 from "/assets/images/markus-spiske-kK7uPfb2YWU-unsplash.jpg";
import servico4 from "/assets/images/xin-Q5hVR77WgZg-unsplash.jpg";
import servico5 from "/assets/images/hobi-industri-NLBJ2I0lNr4-unsplash.jpg";
import sobre from "/assets/images/image-from-rawpixel-id-6284500-png.png";

export const logoImg = logo;
export const fundoImgHd = fundoHd;
export const fundoImgIn1 = fundoIn1;
export const fundoImgIn2 = fundoIn2;
export const setaRImg = setaR;
export const setaLImg = setaL;
export const dinheiroImg = dinheiro;
export const pontoImg = ponto;
export const estrelaImg = estrela;
export const servico1Img = servico1;
export const servico2Img = servico2;
export const servico3Img = servico3;
export const servico4Img = servico4;
export const servico5Img = servico5;
export const sobreImg = sobre;
